/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiforHospital;

import Directories.CommunityDirectory;
import uiForDoctor.*;
import uiForPatient.*;
import Directories.DoctorDirectory;
import Directories.EncounterHistory;
import Directories.HospitalDirectory;
import Directories.PatientDirectory;
import Directories.PersonDirectory;
import assignment.pkg2.Validations;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import smallClasses.City;
import smallClasses.Community;
import smallClasses.Doctor;
import smallClasses.Encounter;
import smallClasses.Hospital;
import smallClasses.House;
import smallClasses.Patient;
import smallClasses.VitalSigns;

/**
 *
 * @author anush
 */
public class createHospital extends javax.swing.JPanel {

    public int hId = 101011;
    /**
     * Creates new form createPatient
     */
    DoctorDirectory doctorList;
    PatientDirectory patientList;
    PersonDirectory personList;
    HospitalDirectory hospitalList;
    CommunityDirectory communityDirectory;
    EncounterHistory encounterHistory;
    Community community;
    Validations v;
    //Patient p;
    
//    public createPatient(){
//        initComponents();
//        
//        //p = new Patient();
//    }
//    
    public createHospital(DoctorDirectory doctorList, PatientDirectory patientList, PersonDirectory personList, HospitalDirectory hospitalList, CommunityDirectory communityDirectory, EncounterHistory encounterHistory){
        initComponents();
        this.doctorList = doctorList;
        this.patientList = patientList;
        this.personList = personList;
        this.hospitalList = hospitalList;
        this.communityDirectory = communityDirectory;
        this.encounterHistory = encounterHistory;
        community = new Community();
        v = new Validations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hospitalName = new javax.swing.JTextField();
        hospitalEmail = new javax.swing.JTextField();
        hospitalPassword = new javax.swing.JTextField();
        hospitalNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hospitalCommunityCode = new javax.swing.JTextField();
        hospitalCity = new javax.swing.JTextField();
        hospitalState = new javax.swing.JTextField();
        hospitalCountry = new javax.swing.JTextField();
        addHospitalButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Hospital Details");

        jLabel2.setText("Name");

        jLabel4.setText("Email");

        jLabel5.setText("Password");

        jLabel6.setText("Phone Number");

        jLabel11.setText("Community Code");

        jLabel12.setText("City");

        jLabel13.setText("State");

        hospitalPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalPasswordActionPerformed(evt);
            }
        });

        jLabel15.setText("Country");

        hospitalCommunityCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalCommunityCodeActionPerformed(evt);
            }
        });

        hospitalState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalStateActionPerformed(evt);
            }
        });

        addHospitalButton.setBackground(new java.awt.Color(204, 204, 255));
        addHospitalButton.setText("Add Hospital");
        addHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHospitalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hospitalCommunityCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(hospitalName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hospitalCountry)
                    .addComponent(hospitalCity, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(hospitalEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(hospitalPassword))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addHospitalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(hospitalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hospitalPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(hospitalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(hospitalCommunityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(hospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hospitalState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(hospitalCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(addHospitalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalCommunityCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalCommunityCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalCommunityCodeActionPerformed

    private void hospitalStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalStateActionPerformed

    private void addHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHospitalButtonActionPerformed
        // TODO add your handling code here:
       try{ 
        
        if (hospitalName.getText() == null
                    || hospitalEmail.getText() == null
                    || hospitalNumber.getText() == null
                    || hospitalPassword.getText() == null
                    || hospitalCommunityCode.getText() == null
                    || hospitalCity.getText() == null 
                    || hospitalState.getText() == null
                    || hospitalCountry.getText() == null) {
                JOptionPane.showMessageDialog(this, "Enter the details");
                return;
            }

            City city = new City();
            city.setCityName(hospitalCity.getText());
            Community communityCode = new Community();
            communityCode.setCommunityCode(Integer.parseInt(hospitalCommunityCode.getText()));
            

            if (v.isValidName(hospitalName.getText())) {
                System.out.println("correct name");
            } else {
                //patientName.requestFocus();
                hospitalName.setText("");
                System.out.println("name incorrect");
            }
            if (v.isValidEmail(hospitalEmail.getText())) {
                System.out.println("correct email");
            } else {
                //patientName.requestFocus();
                hospitalEmail.setText("");
                System.out.println("email incorrect");
            }
            if (v.isValidPhoneNumber(hospitalNumber.getText())) {
                System.out.println("correct number");
                //phoneNumber = Long.parseLong(patientNumber.getText());
            } else {
                //patientName.requestFocus();
                hospitalNumber.setText("");
                System.out.println("number incorrect");
            }
            if (v.onlyDigits(hospitalCommunityCode.getText())) {
                System.out.println("correct aptno");
            } else {
                //patientName.requestFocus();
                hospitalCommunityCode.setText("");
                System.out.println("aptno incorrect");
            }
            if(v.isValidString(hospitalCity.getText())){
                System.out.println("correct city");
            } else {
                //patientName.requestFocus();
                hospitalCity.setText("");
                System.out.println("city incorrect");
            }
            if (v.isValidString(hospitalState.getText())) {
                System.out.println("correct state name");
            } else {
                //patientName.requestFocus();
                hospitalState.setText("");
                System.out.println("state name incorrect");
            }
            if (v.isValidString(hospitalCountry.getText())) {
                System.out.println("correct country name");
            } else {
                //patientName.requestFocus();
                hospitalCountry.setText("");
                System.out.println("country name incorrect");
            }

            if (v.isValidName(hospitalName.getText())
                    && v.isValidEmail(hospitalEmail.getText())
                    && v.isValidPhoneNumber(hospitalNumber.getText())
                    && v.onlyDigits(hospitalCommunityCode.getText())
                    && v.isValidString(hospitalCity.getText())
                    && v.isValidString(hospitalState.getText())
                    && v.isValidString(hospitalCountry.getText())) {
            
        Hospital h = hospitalList.addNewHospitald();
        
        h.setHospitalId(v.getRandomNumber());
        h.setName(hospitalName.getText());
        h.setEmail(hospitalEmail.getText());
        h.setPassword(hospitalPassword.getText());
        h.setPhone_number(hospitalNumber.getText());
        h.setCommunity(communityCode);
        h.setCity(city);
        h.setState(hospitalState.getText());
        h.setCountry(hospitalCountry.getText());
        community.setCommunityCode(v.getRandomNumber());
        community.setCity(city);
        community.setPassword(city.getCityName());
        communityDirectory.addData(community);
        
        JOptionPane.showMessageDialog(this, "Record Saved!");
            } else {
                JOptionPane.showMessageDialog(this, "Enter correct details");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        //patientList.addNewPatient(p);
    }//GEN-LAST:event_addHospitalButtonActionPerformed

    private void hospitalPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHospitalButton;
    private javax.swing.JTextField hospitalCity;
    private javax.swing.JTextField hospitalCommunityCode;
    private javax.swing.JTextField hospitalCountry;
    private javax.swing.JTextField hospitalEmail;
    private javax.swing.JTextField hospitalName;
    private javax.swing.JTextField hospitalNumber;
    private javax.swing.JTextField hospitalPassword;
    private javax.swing.JTextField hospitalState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
